server:
  servlet:
    context-path: /wakanda/app/poc-lessons-skill
spring:
  datasource:
    url: ${WAKANDA_DB_URL}
    username: ${WAKANDA_DB_USERNAME}
    password: ${WAKANDA_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: ${DATASOURCE_MAX_LIFETIME:3000}
      minimum-idle: 1
      maximum-pool-size: ${DATASOURCE_MAXIMUM_POOL_SIZE:5}
      idle-timeout: ${DATASOURCE_IDLE_TIMEOUT:5000}
      max-lifetime: ${DATASOURCE_MAX_LIFETIME:1000}
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
